import type { MasterSettingsSnapshot, MasterSettingsSection } from "@nr/shared";
import { Activity, Globe2, KeyRound, Server } from "lucide-react";
import { Card } from "../ui/Card";
import { StatusBadge } from "../ui/StatusBadge";

export function SettingsRuntimeStatus({ section, snapshot }: { section: MasterSettingsSection; snapshot: MasterSettingsSnapshot }) {
  if (section === "network") return <Card as="section" className="settings-runtime-status"><header><Globe2 size={17} /><div><h3>اتصال شناسایی‌شده</h3><p>این مقادیر فقط خواندنی و مربوط به درخواست فعلی هستند.</p></div></header><dl><div><dt>Host</dt><dd dir="ltr">{snapshot.connection.host}</dd></div><div><dt>Protocol</dt><dd>{snapshot.connection.protocol.toUpperCase()}</dd></div><div><dt>Port</dt><dd>{snapshot.connection.port ?? "—"}</dd></div><div><dt>HTTPS</dt><dd>{snapshot.connection.https ? "فعال" : "غیرفعال"}</dd></div></dl></Card>;
  if (section === "tls") return <Card as="section" className="settings-runtime-status"><header><KeyRound size={17} /><div><h3>وضعیت گواهی</h3><p>کلید خصوصی خوانده یا به مرورگر ارسال نمی‌شود.</p></div><StatusBadge tone={snapshot.certificate.status === "ACTIVE" ? "healthy" : snapshot.certificate.status === "MISSING" ? "warning" : "danger"}>{snapshot.certificate.status}</StatusBadge></header><dl><div><dt>انقضا</dt><dd>{snapshot.certificate.expiresAt ? new Date(snapshot.certificate.expiresAt).toLocaleString("fa-IR") : "—"}</dd></div><div><dt>Subject</dt><dd dir="ltr">{snapshot.certificate.subject || "—"}</dd></div><div><dt>آخرین بررسی</dt><dd>{new Date(snapshot.certificate.lastCheckedAt).toLocaleString("fa-IR")}</dd></div></dl></Card>;
  if (section === "xray") return <Card as="section" className="settings-runtime-status"><header><Activity size={17} /><div><h3>وضعیت Xray</h3><p>نسخه‌ها و nodeها مستقیماً از state ثبت‌شده سرورها.</p></div><StatusBadge tone={snapshot.diagnostics.xray.total && snapshot.diagnostics.xray.running === snapshot.diagnostics.xray.total ? "healthy" : "warning"}>{snapshot.diagnostics.xray.running} / {snapshot.diagnostics.xray.total} RUNNING</StatusBadge></header><dl><div><dt>نسخه نصب/اجرا</dt><dd dir="ltr">{snapshot.diagnostics.xray.versions.join(" · ") || "—"}</dd></div><div><dt>Node / Server</dt><dd>{snapshot.diagnostics.xray.nodes.join(" · ") || "—"}</dd></div><div><dt>Config Valid</dt><dd>{snapshot.diagnostics.xray.configValid.toLocaleString("fa-IR")}</dd></div><div><dt>API Integration</dt><dd>{snapshot.diagnostics.agents.online ? "Agent connected" : "Unavailable"}</dd></div></dl><div className="runtime-pipeline"><Server size={14} /><span>desired state → validate → backup → hot apply / restart → health check → rollback</span></div></Card>;
  return null;
}
